[green_agent]
agentbeats_id = "019bc2a8-7f40-74f0-87fe-17e62c7ad027"
env = { API_KEY = "${GITHUB_SECRET_NAME}", GOOGLE_API_KEY="${GOOGLE_API_KEY}", OPENAI_API_KEY="${OPENAI_API_KEY}", LOG_LEVEL = "INFO" }

[[participants]]
agentbeats_id = ""
name = "forecaster"
env = { API_KEY = "${GITHUB_SECRET_NAME}", GOOGLE_API_KEY="${GOOGLE_API_KEY}", OPENAI_API_KEY="${OPENAI_API_KEY}", LOG_LEVEL = "INFO" }

[config]
num_rounds = 1

